export const ACTION_GET_ALL_ADS = "ACTION_GET_ALL_ADS"
export const ACTION_GET_AD_QUERIES = "ACTION_GET_AD_QUERIES"
export const SET_CURRENT_AD_QUERY = "SET_CURRENT_AD_QUERY"
export const ACTION_UUU = "ACTION_UUU"
